@host=https://localhost:7202

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZjE5N2M3NS0xN2FhLTRmMWEtOWUwYy1mZmNhN2MzMWExOTQiLCJnaXZlbl9uYW1lIjoiUGVkcm8iLCJmYW1pbHlfbmFtZSI6IkdydWxsb24iLCJqdGkiOiIwM2I4ZGY5YS0yYzE3LTQ3YTMtYmQyNi00NTdhZTQ4NzQ4NTciLCJleHAiOjE2NzcyNTY3MzksImlzcyI6IlJlZ2IiLCJhdWQiOiJSZWdiIn0.v9l_VIJExclsuytRIBMDiIBMuSIhC71b173vv9gsO6g

@hostId=asdf

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}