@host=https://localhost:7202

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZTE3MTRiOS0wNDY1LTRhMGQtYWY3MC1mNWFmOGMyOTYxNzUiLCJnaXZlbl9uYW1lIjoiam9yZ2UiLCJmYW1pbHlfbmFtZSI6IkdydWxsb24iLCJqdGkiOiJlN2YzYjU0ZC1jMGUzLTQ5ZWYtOGFhOS1lMWNjZDRlZTU5ZGMiLCJleHAiOjE2NzgyOTk2MzMsImlzcyI6IlJlZ2IiLCJhdWQiOiJSZWdiIn0.Qg7SiI9Y8ZKcxosWyAuYOjq-HprWePi1l83BMYYOW3Q

@hostId=asdf

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}