@host=http://localhost:5179
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YzhjMWZmZS1jYmE1LTQ3NWEtYTJjYS1mMDQyZWZhNzZhNzciLCJnaXZlbl9uYW1lIjoiQW1pa28iLCJmYW1pbHlfbmFtZSI6IkRhcmsiLCJqdGkiOiIyYzg4Nzk4Yy01YWIzLTRkYTQtYTJiYS1jMDlhYjFjMjc4MTAiLCJleHAiOjE2NzI5MzUwMTMsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.TatchvZ83jpihAqvxhqvRwq6oVMqgww8w830w_GiKLI
@hostId=asdf

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}