@host=http://localhost:81
POST  {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "jorge",
    "lastName": "Grullon",
    "email": "jorge@gmail.com",
    "password": "1234"
}


