@host=https://localhost:81
POST  {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Pedro",
    "lastName": "Grullon",
    "email": "Pedro@gmail.com",
    "password": "1234"
}


