@host=https://localhost:7202
GET  {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZjlmNDlkNy1iOTE4LTQ2NjgtODBmZC1mNzVhYWI2YWIxMzIiLCJnaXZlbl9uYW1lIjoiam9yZ2UiLCJmYW1pbHlfbmFtZSI6IkdydWxsb24iLCJqdGkiOiIzNjk5MTIyNS00ZGZiLTRlNzgtYjkwOC0wZTM0N2E5Njg5MDkiLCJleHAiOjE2NzgyODUxMTcsImlzcyI6IlJlZ2IiLCJhdWQiOiJSZWdiIn0.o3lyBIzRAPby8PG3I_R_L8dmTxElMCx8tRtmDvK_MaY