@host=https://localhost:7202
GET  {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkM2QzMWZhNy00ZmRhLTQwYjQtYjE3OC1jMjBlMjc0ODk5YzAiLCJnaXZlbl9uYW1lIjoiUGVkcm8iLCJmYW1pbHlfbmFtZSI6IkdydWxsb24iLCJqdGkiOiJmY2M3Y2I3NC1kZjA0LTQ3MjgtYTNiOC03M2M1M2EwNDNhM2YiLCJleHAiOjE2NzcxNjc3ODQsImlzcyI6IlJlZ2IiLCJhdWQiOiJSZWdiIn0.yD_MF1hnTTyh3K7RbEJF9Yo21pO7maEWjaIU0IdK1Nw